export const IS_COLLAPSE_MENU = 'control.IS_COLLAPSE_MENU';
export const IS_OPEN_PANEL_INFO = 'control.IS_OPEN_PANEL_INFO';
export const INSERT_COMPONENT_PANEL_INFO =
  'control.INSERT_COMPONENT_PANEL_INFO';
export const TOGGLE_COMMON_DIALOG_VISIBILITY =
  'control.TOGGLE_COMMON_DIALOG_VISIBILITY';
export const TOGGLE_MASTER_PAGE_BUSY_INDICATOR =
  'control.TOGGLE_MASTER_PAGE_BUSY_INDICATOR';

export const SHOW_INFO_MESSAGE = 'control.SHOW_INFO_MESSAGE';
export const ENABLE_STATUS_BAR = 'control.ENABLE_STATUS_BAR';
export const DISABLE_STATUS_BAR = 'control.DISABLE_STATUS_BAR';
export const CLEAR_INFO_MESSAGE = 'control.CLEAR_INFO_MESSAGE';
export const OPEN_INFO_PANEL_WITH_COMPONENT =
  'control.OPEN_INFO_PANEL_WITH_COMPONENT';
export const CLOSE_INFO_PANEL_WITH_COMPONENT =
  'control.CLOSE_INFO_PANEL_WITH_COMPONENT';
