export const IS_COLLAPSE_MENU = 'control.IS_COLLAPSE_MENU';
export const IS_OPEN_PANEL_INFO = 'control.IS_OPEN_PANEL_INFO';
export const INSERT_COMPONENT_PANEL_INFO =
  'control.INSERT_COMPONENT_PANEL_INFO';
export const TOGGLE_COMMON_DIALOG_VISIBILITY =
  'control.TOGGLE_COMMON_DIALOG_VISIBILITY';
