export const GET_CUSTOMERS_LIST_PAGINATED =
  'customer.GET_CUSTOMERS_LIST_PAGINATED';
export const UPDATE_CUSTOMERS_LIST = 'customer.UPDATE_CUSTOMERS_LIST';
export const UPDATE_CUSTOMERS_LIST_PAGINATION_INFO =
  'customer.UPDATE_CUSTOMERS_LIST_PAGINATION_INFO';
export const SEARCH_CUSTOMER = 'customer.SEARCH_CUSTOMER';
export const SEARCH_CUSTOMER_BY_STORE = 'customer.SEARCH_CUSTOMER_BY_STORE';
export const TOGGLE_NEW_CUSTOMER_FORM = 'customer.TOGGLE_NEW_CUSTOMER_FORM';
export const CUSTOMER_FORM_STORE_AUTOCOMPLETE_TEXT =
  'customer.CUSTOMER_FORM_STORE_AUTOCOMPLETE_TEXT';
export const UPDATE_CUSTOMER_FORM_STORE_AUTOCOMPLETE_LIST =
  'customer.UPDATE_CUSTOMER_FORM_STORE_AUTOCOMPLETE_LIST';
