export const GET_CUSTOMERS_LIST_PAGINATED =
  'customer.GET_CUSTOMERS_LIST_PAGINATED';
export const UPDATE_CUSTOMERS_LIST = 'customer.UPDATE_CUSTOMERS_LIST';
export const UPDATE_CUSTOMERS_LIST_PAGINATION_INFO =
  'customer.UPDATE_CUSTOMERS_LIST_PAGINATION_INFO';
export const SEARCH_CUSTOMER = 'customer.SEARCH_CUSTOMER';
