export const GET_DEALERS_LIST = 'dealer.GET_DEALERS_LIST';
export const GET_DEALERS_LIST_PAGINATED = 'dealer.GET_DEALERS_LIST_PAGINATED';
export const GET_AND_SELECT_DEALER_BY_ID = 'dealer.GET_AND_SELECT_DEALER_BY_ID';
export const UPDATE_DEALERS_LIST = 'dealer.UPDATE_DEALERS_LIST';
export const SAVE_NEW_DEALER = 'dealer.SAVE_NEW_DEALER';
export const UPDATE_DEALER = 'dealer.UPDATE_DEALER';
export const TOGGLE_NEW_DEALER_FORM = 'dealer.TOGGLE_NEW_DEALER_FORM';
export const SELECTED_DEALER = 'dealer.SELECTED_DEALER';
export const GET_STORES_BY_DEALER = 'dealer.GET_STORES_BY_DEALER';
export const SEARCH_DEALER = 'dealer.SEARCH_DEALER';
export const DELETE_DEALER_BY_ID = 'dealer.DELETE_DEALER_BY_ID';

/// Updates pagination (don't confuse with PAGINATION_INFO)
export const UPDATE_DEALER_LIST_PAGINATION =
  'dealer.UPDATE_DEALER_LIST_PAGINATION';
export const IS_OPEN_PANEL_WITH_DEALER_DETAILS =
  'dealer.IS_OPEN_PANEL_WITH_DEALER_DETAILS';
export const SET_DEALER_STORES = 'dealer.SET_DEALER_STORES';
/// Updates pagination INFO inside pagination
export const UPDATE_DEALER_LIST_PAGINATION_INFO =
  'dealer.UPDATE_DEALER_LIST_PAGINATION_INFO';

export const UPDATE_DEALER_STORE = 'dealer.UPDATE_DEALER_STORE';
export const SET_UPDATE_DEALER_STORE = 'dealer.SET_UPDATE_DEALER_STORE';
export const ADD_STORE_TO_CURRENT_DEALER = 'dealer.ADD_STORE_TO_CURRENT_DEALER';
export const ADD_NEW_STORE_TO_CURRENT_DEALER =
  'dealer.ADD_NEW_STORE_TO_CURRENT_DEALER';
