export const MANAGING_PANEL_CONTENT = 'productSettings.MANAGING_PANEL_CONTENT';
export const SAVE_NEW_OPTION_GROUP = 'productSettings.SAVE_NEW_OPTION_GROUP';

export const GET_ALL_OPTION_GROUPS_LIST =
  'productSettings.GET_ALL_OPTION_GROUPS_LIST';
export const UPDATE_OPTION_GROUP_LIST =
  'productSettings.UPDATE_OPTION_GROUP_LIST';
export const CHANGE_TARGET_OPTION_GROUP_FOR_UNITS_EDIT =
  'productSettings.CHANGE_TARGET_OPTION_GROUP_FOR_UNITS_EDIT';
