export const MANAGING_PANEL_CONTENT = 'productSettings.MANAGING_PANEL_CONTENT';
export const SAVE_NEW_OPTION_GROUP = 'productSettings.SAVE_NEW_OPTION_GROUP';

export const GET_ALL_OPTION_GROUPS_LIST =
  'productSettings.GET_ALL_OPTION_GROUPS_LIST';
export const UPDATE_OPTION_GROUP_LIST =
  'productSettings.UPDATE_OPTION_GROUP_LIST';
export const CHANGE_TARGET_OPTION_GROUP_FOR_UNITS_EDIT =
  'productSettings.CHANGE_TARGET_OPTION_GROUP_FOR_UNITS_EDIT';
export const MODIFY_OPTION_UNITS_ORDER =
  'productSettings.MODIFY_OPTION_UNITS_ORDER';
export const CHANGE_TARGET_OPTIONUNIT =
  'productSettings.CHANGE_TARGET_OPTIONUNIT';
export const UPDATE_OPTION_UNIT = 'productSettings.UPDATE_OPTION_UNIT';
export const SAVE_NEW_OPTION_UNIT = 'productSettings.SAVE_NEW_OPTION_UNIT';
export const TOGGLE_OPTION_UNIT_FORM_VISIBILITY =
  'productSettings.TOGGLE_OPTION_UNIT_FORM_VISIBILITY';
export const DELETE_OPTION_UNIT_BY_ID =
  'productSettings.DELETE_OPTION_UNIT_BY_ID';
export const GET_AND_SELECT_OPTION_GROUP_BY_ID =
  'productSettings.GET_AND_SELECT_OPTION_GROUP_BY_ID';
export const UPDATE_SEARCH_WORD_OPTION_GROUP =
  'productSettings.UPDATE_SEARCH_WORD_OPTION_GROUP';
export const GET_BY_SEARCH_OPTION_GROUPS =
  'productSettings.GET_BY_SEARCH_OPTION_GROUPS';
