export const API_GET_ALL_PRODUCT_CATEGORY =
  'product.API.API_GET_ALL_PRODUCT_CATEGORY';
export const SUCCESS_GET_ALL_PRODUCT_CATEGORY =
  'product.SUCCESS_GET_ALL_PRODUCT_CATEGORY';
export const API_ADD_NEW_PRODUCT_CATEGORY =
  'product.API.API_ADD_NEW_PRODUCT_CATEGORY';
export const SUCCESS_ADD_NEW_PRODUCT_CATEGORY =
  'product.SUCCESS_ADD_NEW_PRODUCT_CATEGORY';
export const API_UPDATE_PRODUCT_CATEGORY =
  'product.API.API_UPDATE_PRODUCT_CATEGORY';
export const SUCCESS_UPDATE_PRODUCT_CATEGORY =
  'product.SUCCESS_UPDATE_PRODUCT_CATEGORY';
export const API_DELETE_PRODUCT_CATEGORY =
  'product.API.API_DELETE_PRODUCT_CATEGORY';
export const SUCCESS_DELETE_PRODUCT_CATEGORY =
  'product.SUCCESS_DELETE_PRODUCT_CATEGORY';
export const API_GET_PRODUCT_CATEGORY_BY_ID =
  'product.API.API_GET_PRODUCT_CATEGORY_BY_ID';

export const CHANGE_MANAGING_PANEL_CONTENT =
  'product.panelManagement.CHANGE_MANAGING_PANEL_CONTENT';

export const CHANGE_TARGET_SINGELE_MANAGING_PRODUCT =
  'product.singleProductManaging.CHANGE_TARGET_SINGELE_MANAGING_PRODUCT';
export const CHOOSE_PRODUCT_CATEGORY = 'product.CHOOSE_PRODUCT_CATEGORY';

export const API_GET_MEASUREMENTS_BY_PRODUCT =
  'product.API.API_GET_MEASUREMENTS_BY_PRODUCT';
export const SUCCESS_GET_MEASUREMENTS_BY_PRODUCT =
  'product.SUCCESS_GET_MEASUREMENTS_BY_PRODUCT';
export const SET_CHOOSE_PRODUCT_CATEGORY_ID =
  'product.SET_CHOOSE_PRODUCT_CATEGORY_ID';

export const UPDATE_OPTIONGROUPS_LIST =
  'product.productCategoryDetails.UPDATE_OPTIONGROUPS_LIST';
export const API_SAVE_UPDATED_PRODUCT_GROUPS =
  'product.API.productCategoryDetails.API_SAVE_UPDATED_PRODUCT_GROUPS';
export const TOGGLE_IS_DETAILSFORM_DISABLED =
  'product.productCategoryDetails.TOGGLE_IS_DETAILSFORM_DISABLED';
