export const API_GET_ALL_PRODUCT_CATEGORY =
  'product.API_GET_ALL_PRODUCT_CATEGORY';
export const SUCCESS_GET_ALL_PRODUCT_CATEGORY =
  'product.SUCCESS_GET_ALL_PRODUCT_CATEGORY';
export const API_ADD_NEW_PRODUCT_CATEGORY =
  'product.API_ADD_NEW_PRODUCT_CATEGORY';
export const SUCCESS_ADD_NEW_PRODUCT_CATEGORY =
  'product.SUCCESS_ADD_NEW_PRODUCT_CATEGORY';
export const API_UPDATE_PRODUCT_CATEGORY =
  'product.API_UPDATE_PRODUCT_CATEGORY';
export const SUCCESS_UPDATE_PRODUCT_CATEGORY =
  'product.SUCCESS_UPDATE_PRODUCT_CATEGORY';
export const API_DELETE_PRODUCT_CATEGORY =
  'product.API_DELETE_PRODUCT_CATEGORY';
export const SUCCESS_DELETE_PRODUCT_CATEGORY =
  'product.SUCCESS_DELETE_PRODUCT_CATEGORY';
