export const GET_ALL_PRODUCT_CATEGORY = 'product.GET_ALL_PRODUCT_CATEGORY';
export const SUCCESS_GET_ALL_PRODUCT_CATEGORY =
  'product.SUCCESS_GET_ALL_PRODUCT_CATEGORY';
export const ADD_NEW_PRODUCT_CATEGORY = 'product.ADD_NEW_PRODUCT_CATEGORY';
export const SUCCESS_ADD_NEW_PRODUCT_CATEGORY =
  'product.SUCCESS_ADD_NEW_PRODUCT_CATEGORY';
export const UPDATE_PRODUCT_CATEGORY = 'product.UPDATE_PRODUCT_CATEGORY';
export const SUCCESS_UPDATE_PRODUCT_CATEGORY =
  'product.SUCCESS_UPDATE_PRODUCT_CATEGORY';
export const DELETE_PRODUCT_CATEGORY = 'product.DELETE_PRODUCT_CATEGORY';
export const SUCCESS_DELETE_PRODUCT_CATEGORY =
  'product.SUCCESS_DELETE_PRODUCT_CATEGORY';
